//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_G1_L1.Language {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS_G1_L1.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version : 2.0.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copie terminée.
        /// </summary>
        public static string CopieEnd {
            get {
                return ResourceManager.GetString("CopieEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        public static string CreateJobBack {
            get {
                return ResourceManager.GetString("CreateJobBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous encrypter votre sauvegarde ?.
        /// </summary>
        public static string CreateJobEncrypt {
            get {
                return ResourceManager.GetString("CreateJobEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du fichier de destination.
        /// </summary>
        public static string CreateJobFileDestination {
            get {
                return ResourceManager.GetString("CreateJobFileDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du fichier source.
        /// </summary>
        public static string CreateJobFileSource {
            get {
                return ResourceManager.GetString("CreateJobFileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du dossier de destination.
        /// </summary>
        public static string CreateJobFolderDestination {
            get {
                return ResourceManager.GetString("CreateJobFolderDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du dossier source.
        /// </summary>
        public static string CreateJobFolderSource {
            get {
                return ResourceManager.GetString("CreateJobFolderSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la sauvegarde.
        /// </summary>
        public static string CreateJobNameSave {
            get {
                return ResourceManager.GetString("CreateJobNameSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregister le travail.
        /// </summary>
        public static string CreateJobSaveJob {
            get {
                return ResourceManager.GetString("CreateJobSaveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin.
        /// </summary>
        public static string CreateJobSource {
            get {
                return ResourceManager.GetString("CreateJobSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un travail de sauvegarde.
        /// </summary>
        public static string CreateJobTitle {
            get {
                return ResourceManager.GetString("CreateJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de travail de sauvegarde.
        /// </summary>
        public static string CreateJobTypeFullDif {
            get {
                return ResourceManager.GetString("CreateJobTypeFullDif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde.
        /// </summary>
        public static string CreateJobTypeSave {
            get {
                return ResourceManager.GetString("CreateJobTypeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous vraiment surpprimer ce travail de sauvegarde ?.
        /// </summary>
        public static string DeleteJobConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteJobConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer le travail.
        /// </summary>
        public static string DeleteJobDeleteJob {
            get {
                return ResourceManager.GetString("DeleteJobDeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde encrypter .
        /// </summary>
        public static string DeleteJobEncrypt {
            get {
                return ResourceManager.GetString("DeleteJobEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression du travail de sauvegarde.
        /// </summary>
        public static string DeleteJobMessage {
            get {
                return ResourceManager.GetString("DeleteJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un travail de sauvegarde.
        /// </summary>
        public static string DeleteJobTitle {
            get {
                return ResourceManager.GetString("DeleteJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentiel.
        /// </summary>
        public static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension d&apos;encryptage.
        /// </summary>
        public static string EncryptionExtension {
            get {
                return ResourceManager.GetString("EncryptionExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez rentrer le chemin du fichier/dossier de destination..
        /// </summary>
        public static string ErrorDestinationEmpty {
            get {
                return ResourceManager.GetString("ErrorDestinationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez renseigner votre choix concernant l&apos;encryptage de votre sauvegarde..
        /// </summary>
        public static string ErrorEncryptEmpty {
            get {
                return ResourceManager.GetString("ErrorEncryptEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez rentrer le nom de la sauvegarde..
        /// </summary>
        public static string ErrorNameSaveEmpty {
            get {
                return ResourceManager.GetString("ErrorNameSaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un fichier de destination.
        /// </summary>
        public static string ErrorSelectFileDestination {
            get {
                return ResourceManager.GetString("ErrorSelectFileDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un fichier source.
        /// </summary>
        public static string ErrorSelectFileSource {
            get {
                return ResourceManager.GetString("ErrorSelectFileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un dossier de destination.
        /// </summary>
        public static string ErrorSelectFolderDestination {
            get {
                return ResourceManager.GetString("ErrorSelectFolderDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner un dossier source.
        /// </summary>
        public static string ErrorSelectFolderSource {
            get {
                return ResourceManager.GetString("ErrorSelectFolderSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez rentrer le chemin du fichier/dossier source..
        /// </summary>
        public static string ErrorSourceEmpty {
            get {
                return ResourceManager.GetString("ErrorSourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez rentrer le type de sauvegarde..
        /// </summary>
        public static string ErrorTypeEmpty {
            get {
                return ResourceManager.GetString("ErrorTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez rentrer le type de travail de sauvegarde..
        /// </summary>
        public static string ErrorTypeOfWork {
            get {
                return ResourceManager.GetString("ErrorTypeOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dossier.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entier.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux.
        /// </summary>
        public static string MainWindowJob {
            get {
                return ResourceManager.GetString("MainWindowJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string MainWindowJobAdd {
            get {
                return ResourceManager.GetString("MainWindowJobAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string MainWindowJobDelete {
            get {
                return ResourceManager.GetString("MainWindowJobDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string MainWindowJobModify {
            get {
                return ResourceManager.GetString("MainWindowJobModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lire.
        /// </summary>
        public static string MainWindowJobRead {
            get {
                return ResourceManager.GetString("MainWindowJobRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail séléctionné :.
        /// </summary>
        public static string MainWindowJobSelected {
            get {
                return ResourceManager.GetString("MainWindowJobSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string MainWindowParameters {
            get {
                return ResourceManager.GetString("MainWindowParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde.
        /// </summary>
        public static string MainWindowSave {
            get {
                return ResourceManager.GetString("MainWindowSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille maximum du fichier.
        /// </summary>
        public static string MaximumFileSize {
            get {
                return ResourceManager.GetString("MaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification d&apos;un travail de sauvegarde.
        /// </summary>
        public static string ModifyJobTitle {
            get {
                return ResourceManager.GetString("ModifyJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NON.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de sauvegarde :.
        /// </summary>
        public static string NumberSaveTitle {
            get {
                return ResourceManager.GetString("NumberSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autre taille maximum.
        /// </summary>
        public static string OtherMaximumFileSize {
            get {
                return ResourceManager.GetString("OtherMaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue :.
        /// </summary>
        public static string ParamsLanguage {
            get {
                return ResourceManager.GetString("ParamsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de sauvegarde par défaut :.
        /// </summary>
        public static string ParamsPathDefault {
            get {
                return ResourceManager.GetString("ParamsPathDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres généraux de l&apos;application.
        /// </summary>
        public static string ParamsTitle {
            get {
                return ResourceManager.GetString("ParamsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de logs :.
        /// </summary>
        public static string ParamsTypeLogs {
            get {
                return ResourceManager.GetString("ParamsTypeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider les paramètres.
        /// </summary>
        public static string ParamsValidate {
            get {
                return ResourceManager.GetString("ParamsValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension logiciel prioritaire.
        /// </summary>
        public static string PriorityExtension {
            get {
                return ResourceManager.GetString("PriorityExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer le travail de sauvegarde.
        /// </summary>
        public static string ReadJobConfirm {
            get {
                return ResourceManager.GetString("ReadJobConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur le travail de sauvegarde.
        /// </summary>
        public static string ReadJobTitle {
            get {
                return ResourceManager.GetString("ReadJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer la sauvegarde.
        /// </summary>
        public static string SaveConfirm {
            get {
                return ResourceManager.GetString("SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cryptage :.
        /// </summary>
        public static string SaveParamsEncrypt {
            get {
                return ResourceManager.GetString("SaveParamsEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs : .
        /// </summary>
        public static string SaveParamsLogs {
            get {
                return ResourceManager.GetString("SaveParamsLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres de sauvegarde :.
        /// </summary>
        public static string SaveParamsSave {
            get {
                return ResourceManager.GetString("SaveParamsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail terminé.
        /// </summary>
        public static string WorkCompleted {
            get {
                return ResourceManager.GetString("WorkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de destination.
        /// </summary>
        public static string WorkDestination {
            get {
                return ResourceManager.GetString("WorkDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryptage.
        /// </summary>
        public static string WorkEncrypt {
            get {
                return ResourceManager.GetString("WorkEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier/Dossier.
        /// </summary>
        public static string WorkFileFolder {
            get {
                return ResourceManager.GetString("WorkFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du travail.
        /// </summary>
        public static string WorkNameJob {
            get {
                return ResourceManager.GetString("WorkNameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin source.
        /// </summary>
        public static string WorkSource {
            get {
                return ResourceManager.GetString("WorkSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des travaux de sauvegarde.
        /// </summary>
        public static string WorkTitle {
            get {
                return ResourceManager.GetString("WorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de travail.
        /// </summary>
        public static string WorkType {
            get {
                return ResourceManager.GetString("WorkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OUI.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
